export const FETCH_COMMENTS_STARTED = '[COMMENTS] FETCH_COMMENTS_STARTED'
export const FETCH_COMMENTS_SUCCESS = '[COMMENTS] FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = '[COMMENTS] FETCH_COMMENTS_FAILURE'